# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
