# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')])),
                ('info', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
