# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180913_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='姓名',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100, unique=True, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
