# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 03:42
from __future__ import unicode_literals

import One2Many.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One2Many', '0005_auto_20180914_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=models.SET(One2Many.models.fn), to='One2Many.UserType'),
        ),
    ]
