# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToMany', '0002_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OneToMany.UserType'),
            preserve_default=False,
        ),
    ]
